name: 'Test Workflow'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: replace secrets in yaml config
        uses: microsoft/variable-substitution@users/balaga-gayatri/bug-fix
        with:
          files: 'testxml.xml'
        env:
          author: 'Gayatri'
